### Начало регистрации
POST localhost:8000/auth/registration-confirm-code-start
Content-Type: application/json

{
  "auth_email": "pollu0707@yandex.ru",
  "first_name": "Илья",
  "last_name": "Стильный",
  "middle_name": "Михалыч"
}

### Верификация
POST localhost:8000/auth/registration-confirm-code-finish
Content-Type: application/json

{
  "token": "1a906272-8366-4afc-8214-193bedfa41e6",
  "confirm_code": "213709"
}
